dist_etcpointload_DATA += \
                       etc/common/data.dat \
					   etc/common/testStations.nc \
					   etc/common/units.conf \
					   etc/felt/dataprovider.conf \
					   etc/felt/fimexreader.xml \
					   etc/felt/leveladditions.conf \
					   etc/felt/levelparameter.conf \
					   etc/felt/load.conf \
					   etc/felt/validtime.conf \
					   etc/felt/valueparameter.conf \
					   etc/grib1/data.grib \
					   etc/grib1/dataprovider.conf \
					   etc/grib1/gribreader.xml \
					   etc/grib1/leveladditions1.conf \
					   etc/grib1/levelparameter1.conf \
					   etc/grib1/load.conf \
					   etc/grib1/stations.nc \
					   etc/grib1/valueparameter1.conf \
					   etc/grib2/data.grib \
					   etc/grib2/dataprovider.conf \
					   etc/grib2/gribreader.xml \
					   etc/grib2/leveladditions1.conf \
					   etc/grib2/leveladditions2.conf \
					   etc/grib2/levelparameter1.conf \
					   etc/grib2/levelparameter2.conf \
					   etc/grib2/load.conf \
					   etc/grib2/stations.nc \
					   etc/grib2/valueparameter1.conf \
					   etc/grib2/valueparameter2.conf \
					   etc/netcdf/data.nc \
					   etc/netcdf/leveladditions.conf \
					   etc/netcdf/levelparameter.conf \
					   etc/netcdf/load.conf \
					   etc/netcdf/stations.nc \
					   etc/netcdf/valueparameter.conf
